## Tensors

In [6]:
import torch 
import numpy as np


### Tensor initizialization

In [84]:
## From an array or np array
data_x = [[1,2],[3,4]]
tensor_x = torch.tensor(data_x)
numpy_data_x = np.array(data_x)
tensor_from_numpy = torch.tensor(numpy_data_x)
print(tensor_from_numpy)
print(tensor_x)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [85]:
# From another tensor

## Notice that we retain the shape and data type but not the data if we use ones_like
## We could override the the data type as well if we'd  like
print(torch.tensor(tensor_x))
print(torch.ones_like(tensor_x))
print(torch.rand_like(tensor_x, dtype=torch.float))


tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.3676, 0.8695],
        [0.5883, 0.7836]])


/var/folders/4l/w_wch_6x0s5bgvtbr5vnl6qc0000gn/T/ipykernel_2987/4165640290.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(torch.tensor(tensor_x))


In [86]:
# what is shape?
# shape determines the dimensionality of the vector
shape = (2,3,)
torch.ones(shape)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Attributes

In [87]:
print(f"Shape of tensor: {tensor_x.shape}")
print(f"Datatype of tensor: {tensor_x.dtype}")
print(f"Device tensor is stored on: {tensor_x.device}") # where on memory tensor is stored

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


### Operations 

In [88]:
## Similar to numpy we can multiply tensors in the following way ( element wise product )
t1 = torch.rand((2,3,))
t2 = torch.rand((2,3,))
t3 = torch.rand((3,2,))
print(t1)
print()
print(t2)
print()
print(t3)
print()
print(t1*t2)
print()
## Matrix multiplication 
print(t1@t3)

## Indexing works the following way

##  We can also concat them along various index

tensor([[0.5184, 0.3083, 0.4658],
        [0.2734, 0.4594, 0.4699]])

tensor([[0.0225, 0.6713, 0.8878],
        [0.6290, 0.8528, 0.1140]])

tensor([[0.7851, 0.9683],
        [0.7206, 0.2345],
        [0.8198, 0.9651]])

tensor([[0.0116, 0.2070, 0.4136],
        [0.1720, 0.3918, 0.0536]])

tensor([[1.0111, 1.0238],
        [0.9309, 0.8260]])


In [89]:
## Indexing works the following way
print(t1[0])
print(t1[1])
print(t1[0,2])
print(t1[0:,1])
print(t1[1:,1])


tensor([0.5184, 0.3083, 0.4658])
tensor([0.2734, 0.4594, 0.4699])
tensor(0.4658)
tensor([0.3083, 0.4594])
tensor([0.4594])


In [ ]:
# Joining tensors
print(torch.cat([tensor_x,tensor_x], dim=1))

## Important Caveats

### Using _ suffixed operations

In [91]:
# In-place operations
# there are some operations that have a _ suffix -> these change the tensor its called on
print(tensor_x)
y = tensor_x.add_(5)


tensor([[1, 2],
        [3, 4]])


tensor([[6, 7],
        [8, 9]])

### Modifying tensor and numpy

In [ ]:
# Tensor and numpy arrays spawned from them share the same memory location - so
# modification of one results in the modification of the other

In [93]:
t = torch.ones(5)
n = t.numpy()
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [94]:
t.add_(3)
print(n)

[4. 4. 4. 4. 4.]


In [98]:
# similarly changes in the numpy array affect the tensor
np.add(n,1, out=n)
print(t)

tensor([5., 5., 5., 5., 5.])


In [101]:
n += 2
print(t)

tensor([7., 7., 7., 7., 7.])
